dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - &latest_py3 3.8

jobs:
  fast_finish: true
  include:
  - python: *latest_py3
    env: LANG=C
  - stage: deploy (to PyPI for tagged commits)
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    after_success: true
    before_deploy:
    - python setup.py sdist bdist_wheel
    deploy:
      provider: pypi
      user: voxpupuliorg
      distributions: sdist bdist_wheel
      skip_cleanup: true
      skip_upload_docs: true
      password:
        secure: "bWWCYcDfGPNbg1YjCHqdLDZjpDwiU7i7VsobHC+iTP+Kur7rt7gfHY4daGp5K8Xc/Er4fIJt5wcxpvdnivxce+W1lpVvGOOnYvHxl06Jd41Nj6wfYfUn058G0e5jyT8hfc/NllJKq12gqrOKKFO9m1vLelgscVlaO7S3XyPVvBI="
      on:
        tags: true
        all_branches: true

cache: pip

install:
  - pip install -r requirements-test.txt
script:
  - py.test --cov pypuppetdb --pep8 --mypy --strict
  - bandit -r pypuppetdb
after_success:
  - coveralls
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
